### ISSUE TITLE
refreshGuestToken() runs indefinitely (and stacks!)

### ISSUE THREAD

**Issue by gamma613** [preset-io/frontend-sdk#16]
In our react application, I've observed that superset embeds will continue running `refreshGuestToken()` after I've left the page that has the embed.

What's more, if I re-visit a page embedding a dashboard multiple times, it has a stacking effect - ie: if I visit the dashboard 6 times, it will now make 6 calls to `refreshGuestToken()`.

I've tried calling `dashboard.unmount()` when my page unloads - which successfully removes the iframe, but it doesn't cause the `setTimeout` for `refreshGuestToken()` to be cancelled.

Not sure what other things could be floating around in memory as well.

**Comment by Vitor-Avila** [comment]
Addressed here https://github.com/preset-io/frontend-sdk/pull/22
